### PR TITLE
Add initial support for gpio chardev interface

### PR DESCRIPTION
**Pull request by Mani-Sadhasivam**
This is the start of the series focused on enabling new gpio chardev interface for mraa. The new interface has been separated out from the default 'sysfs' interface for compatibility. So, the API structure has been retained at most.

GPIO's can be accessed using the same numbering scheme offered in sysfs interface. Moving that to the new interface is open for discussion.  

TODO:
1. Add switch for runtime detection of kernel and enabling the appropriate interface
2. Accessing multiple gpio's at the same time
3. GPIO event support
4. Add more examples

### CODE REVIEW

**Comment by arfoll** [comment]
This looks awesome thanks for posting. Im on vacation this week without
much pc access but I'll take a look when I'm back.

On 12 Jul 2017 08:04, "Mani Sadhasivam" <notifications@github.com> wrote:

This is the start of the series focused on enabling new gpio chardev
interface for mraa. The new interface has been separated out from the
default 'sysfs' interface for compatibility. So, the API structure has been
retained at most.

TODO:

   1. Add switch for runtime detection of kernel and enabling the
   appropriate interface
   2. Accessing multiple gpio's at the same time
   3. GPIO event support
   4. Add more examples

------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/intel-iot-devkit/mraa/pull/790
Commit Summary

   - gpio: Add initial support for chardev interface
   - mraa_internal_types: structure alignment fix

File Changes

   - *M* api/mraa.h
   <https://github.com/intel-iot-devkit/mraa/pull/790/files#diff-0> (1)
   - *A* api/mraa/gpio_chardev.h
   <https://github.com/intel-iot-devkit/mraa/pull/790/files#diff-1> (168)
   - *M* examples/CMakeLists.txt
   <https://github.com/intel-iot-devkit/mraa/pull/790/files#diff-2> (4)
   - *A* examples/mraa-gpio_chardev.c
   <https://github.com/intel-iot-devkit/mraa/pull/790/files#diff-3> (156)
   - *M* include/mraa_internal_types.h
   <https://github.com/intel-iot-devkit/mraa/pull/790/files#diff-4> (8)
   - *M* src/CMakeLists.txt
   <https://github.com/intel-iot-devkit/mraa/pull/790/files#diff-5> (1)
   - *A* src/gpio/gpio_chardev.c
   <https://github.com/intel-iot-devkit/mraa/pull/790/files#diff-6> (348)

Patch Links:

   - https://github.com/intel-iot-devkit/mraa/pull/790.patch
   - https://github.com/intel-iot-devkit/mraa/pull/790.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/intel-iot-devkit/mraa/pull/790>, or mute the thread

**Comment by arfoll** [comment]
@Mani-Sadhasivam I had a very quick look and it seems this is using a completely different public API rather than reusing the existing one and extending it. What's your reasoning behind this?

@stefan-andritoiu have you seen this?

**Comment by Mani-Sadhasivam** [comment]
@arfoll  Yes. All of the API's have been prefixed with char for isolating from the old sysfs API. We may change all new API's to use the default one, once the complete support is added. As it still lacks the mandatory interrupt support I thought of co-existing both interfaces for some time.

But, obviously it will get replaced.

**Comment by arfoll** [comment]
Attempt at getting something like this merged in #809. I'm not that happy with the way a few things work in #809 and would love your feedback/help.

**Comment by Propanu** [comment]
Chardev support is now merged and brushed up to some extent. Can we close this?

**Comment by arfoll** [comment]
Closing

**Pull request closed without merging**
