### PR TITLE
Fix interrupt callback args

### PR DESCRIPTION
**Pull request by hansmosh**

### CODE REVIEW

**Comment by arfoll** [comment]
Thanks alot for doing this can you sign this commit off as explained in docs/contributing.md? Following should work:

`git commit --amend --s`
`git push --force`

**Comment by hansmosh** [comment]
Done. I also also added the file name at the beginning of the commit since I saw that on the others.

**Comment by hansmosh** [comment]
This makes #341 work well enough for now but I still can't get a callback to work inside a class. Example:

```
class Gpio():

  def __init__(self):
    ...
    pin.isr(mraa.EDGE_BOTH, callback, self)

  def callback(self):
    print("we did it")
```

**Comment by arfoll** [comment]
Merged with 51436f6a0aaa16d555b58d12eb396f8dbc181731, thanks alot for the fix. I don't know enough about cpython without investigating more how to make that work though.

**Comment by alext-mkrs** [comment]
@hansmosh please feel free to submit an issue for passing self - so that we can track it and either implement it at some point or maybe someone else will be interested.

**Pull request closed without merging**
