### PR TITLE
FT4222 i2c expander GPIO ISR bug fixes

### PR DESCRIPTION
**Pull request by whbruce**
This address issue #435 and updates libft4222 synchronization for improved thread safety.

### CODE REVIEW

**Comment by arfoll** [comment]
This looks good but needs to be rebased ontop of 3b2a5b8429cfbd2622feb9c9738716d5f4a03eab and I didn't want to do it without testing - can you handle that?

**Comment by whbruce** [comment]
I met with @Propanu yesterday and as he no longer has immediate need of his patch we agreed to merge it into my updates at a later date. Looking at the number of conflicts this is a good option. My mistake was not keeping you in the loop. I'll rebase ignoring some of his updates and will add full PCA9555  functionality in a later PR.

**Comment by whbruce** [comment]
Rebased and pushed.

**Comment by whbruce** [comment]
Hold off merging - i have found an issue with PCA9555 support.

**Comment by whbruce** [comment]
Now ready for merge. PR adds support for PCA9555 ISRs and now includes @tingleby's libft4222 dlopen patch.

**Comment by Propanu** [comment]
Thanks @whbruce for taking the time to refactor the code and making GPIO expanders more generic.

**Comment by arfoll** [comment]
Thanks this is merged!

**Pull request closed without merging**
