### PR TITLE
Add support for MIPS-based boards Omega2 and Linkit Smart 7688.

### PR DESCRIPTION
**Pull request by sergev**
Fixed all issued from code review https://github.com/intel-iot-devkit/mraa/pull/829#pullrequestreview-66317406

### CODE REVIEW

**Comment by sergev** [comment]
OK, I'll re-submit a signed pull request. 

Links are already present in README.md: https://github.com/intel-iot-devkit/mraa/pull/831/files/772f0750e96e38e728658701c4d88ce40eaf2d0d#diff-04c6e90faac2675aa89e2176d2eec7d8R44

I'll update docs/index.md as well.

**Comment by sergev** [comment]
Replaced by #832.

**Comment by arfoll** [comment]
FYI you can just rebase your branch the PR is attached to and it will just
update the PR saves you closing/opening every time :)

**Comment by sergev** [comment]
Good to know; thank you.

**Pull request closed without merging**
