### PR TITLE
Sonar automated scans

### PR DESCRIPTION
**Pull request by alext-mkrs**
This brings automated static code analysis scans. Due to the fact we use Docker and not the bare Travis, we can't use Travis' plugin, however I've found ways to avoid losing any functionality because of that :)

For the whole config to work, the following additional configuration steps are necessary:
1. Create organization and project in SonarCloud - done already, https://sonarcloud.io/organizations/mraa-github (key: mraa-github) and https://sonarcloud.io/dashboard?id=mraa-master (key: mraa-master);
1. Create technical account on GH with push permissions for mraa repo - for reporting pull request statuses in the "checks" area. I haven't created this one, assuming @arfoll you'd want to control its credentials, but let me know if you want me to create it and pass credentials to you later.
1. Add several environment variables in Travis:
    1. `GITHUB_TOKEN` (secure) - GH OAuth token for the technical user, with `public_repo` privileges only;
    1. `SONAR_TOKEN` (secure) - this one comes from the SonarCloud org, I have it an can provide it to whoever has Travis admin permissions for mraa. Or if you could provide me with those, I can configure that myself;
    1. `SONAR_ORG`, `SONAR_PROJ_KEY` (may be public) - project and org keys (names) from SonarCloud, see above;
1. Add users to the SonarCloud org's admins: @arfoll, @whbruce, @Propanu, @tingleby - please login there using links above and either GitHub or separate credentials, so that accounts are created. Let me know your usernames there when done - I'll provide you with necessary permissions.

I can do all of that by myself, but I'll need Travis admin permissions for mraa repo and an "ok" for creating the GH technical user (I can pass the credentials for that one using some secure channels to all of you later).

Let meknow if you have any questions and ambiguities.

### CODE REVIEW

**Comment by alext-mkrs** [comment]
Any feedback or plans for merging this one? The Travis failure was in the new sonar-scan target, which fails due to no configuration present (those variables I described above).

**Comment by arfoll** [comment]
@alext-mkrs had a quick look - no need for me to control the account, you're the sonar pro so you may as well control the account. You call it a "technical account" but it's just a normal GH account right? We've already got a few like that on the repo for stats but it's probably best to just create a new one just for this job that only has acccess to the mraa repo.

**Comment by alext-mkrs** [comment]
Sure, sounds good to me. Then it's only the Travis config that's necessary and I've actually just discovered that I can create necessary variables :) (if that were you @afroll - thanks!).

Let me configure it all then.

**Comment by alext-mkrs** [comment]
Ok, so the user would be @mraa-helperbot and I've added the necessary Travis config.

Now if someone could please provide that account with push permissions for mraa repo (so that it can update pull request statuses in the "checks" area), that would be it.

**Comment by alext-mkrs** [comment]
So just to sum up - this one is ready to be merged even right away, as with the config in place it would work even without @mraa-helperbot having push permissions for the repo, but it would look nicer that way (+ would not pollute Travis logs with Java exceptions when trying to set the PR status).

So I'm just waiting for permissions to be assigned and after that I'll rebase and merge this PR.

**Comment by arfoll** [comment]
Ok @mraa-helperbot has the right permissions - should be all good to go? Feel free to merge it.

**Comment by alext-mkrs** [comment]
Great, thanks - I'll do that tomorrow, away from the computer today.

**Comment by alext-mkrs** [comment]
All right - everything works ok now (see example of the status update on this PR). Just needed to log in as the helperbot to accept the organization invitation for permissions to become active. Merging it now.

**Comment by alext-mkrs** [comment]
Merged.

**Comment by alext-mkrs** [comment]
...and just to finalize - the first scan data is in: https://sonarcloud.io/dashboard?id=mraa-master. It detected 7 defects, 5 of which are false-positives I already saw in my fork when preparing this, but two are genuine (but minor) ones :)

**Comment by dnoliver** [comment]
@alext-mkrs did you made sonar work behind a proxy?

I wanted to test this with my own account/project, inside the docker container. But sonar-scanner keeps failing, and I am sure the proxy is the problem (99%  of the problem I ever had working in my company is proxy related)

This command do not work:

```
About to run the scan, the command is:
build-wrapper-linux-x86-64 --out-dir /usr/src/app/build/bw-output make clean all &&     sonar-scanner         --debug         -Dsonar.projectKey=dnoliver-mraa         -Dsonar.projectBaseDir=/usr/src/app         -Dsonar.sources=/usr/src/app         -Dsonar.inclusions='api/**/*,CMakeLists.txt,examples/**/*,imraa/**/*,include/**/*,src/**/*,tests/**/*'         -Dsonar.coverage.exclusions='**/*'         -Dsonar.cfamily.build-wrapper-output=/usr/src/app/build/bw-output         -Dsonar.host.url=https://sonarcloud.io         -Dsonar.organization=dnoliver-github         -Dsonar.login=******         -Dhttp.proxyHost=proxy-chain.intel.com -Dhttp.proxyPort=911 -Dhttp.nonProxyHosts=127.0.0.1,localhost                 -Dsonar.analysis.mode=preview                -Dsonar.github.pullRequest=                -Dsonar.github.repository=                -Dsonar.github.oauth=
```

21:28:51.695 ERROR: SonarQube server [https://sonarcloud.io] can not be reached

**Pull request closed without merging**
