### PR TITLE
docs: updated Python docs index with all supported platforms

### LINKED ISSUE #324: Raspberry Pi link broken
The link to Raspberry Pi from [here](http://iotdk.intel.com/docs/master/mraa/python/#supported-platforms) does not work (404)

### PR DESCRIPTION
**Pull request by alext-mkrs**
Also fixed #324 (broken link to Raspberry Pi page).

### CODE REVIEW

**Comment by arfoll** [comment]
Thanks alot for fix - please add sign off!

**Comment by alext-mkrs** [comment]
Oops  indeed, sure will do in the evening today. Did that directly through GitHub web editor (handy for such small edits) and forgot it doesn't add that by default :smiley:

**Comment by alext-mkrs** [comment]
Added a sign off line.

**Comment by arfoll** [comment]
Thanks a million! Merged with 621bf5266e3762e98347a3c5d4fed6c49339dd1b

**Pull request closed without merging**
