### PR TITLE
examples/i2c_ht16k33.c Example for the ht16k33 LED driver chip

### PR DESCRIPTION
**Pull request by michael-ring**
Signed-off-by: Michael Ring <mail@michael-ring.org>

### CODE REVIEW

**Comment by michael-ring** [comment]
This is a small sample app that switches LED's on a ht16k33. This chip is used on quite some adafruit breakout boards

**Comment by arfoll** [comment]
I'm a bit confused about why you referenced #112 & #113, this is a SPI sample? Is there any reason to have this in here instead of a module in UPM?

**Comment by michael-ring** [comment]
Sorry, this reference was unintentional, the i2c code has no dependency whatsover to the spi code.

This module is test code so that I can test i2c with real hardware on different platforms, testing is easier when the module is within mraa, but I can live with it when you do not want to merge this file into mraa.

**Comment by arfoll** [comment]
As discussed, we already have an i2c sample so this would be duplication. In fact we have 3 python i2c samples... I'm not very good at following my own rules apparently!

**Pull request closed without merging**
