### PR TITLE
fix beaglebone i2c bus 2

### PR DESCRIPTION
**Pull request by mkellner**
Signed-off-by: Michael Kellner <mkellner@intlweb.com>

### CODE REVIEW

**Comment by mkellner** [comment]
This was on a Beaglebone Black running "rcn-ee.net console Ubuntu Image 2015-12-11"

**Comment by arfoll** [comment]
So I don't have a BBB but @tingleby can you confirm?

Also please set user.email & user.name to something valid in git and resubmit with a sign off line as highlighted in CONTRIBUTING.md. Thanks!

**Comment by perkinssyseng** [comment]
I have the same issue with BBB running
Linux beaglebone **4.1.15-ti-rt-r43 #1 SMP PREEMPT RT** Thu Jan 21 20:13:58 UTC 2016 armv7l GNU/Linux.

$ ./mraa-i2c list
Bus   0: id=00 type=linux  default
Bus   1: id=01 type=linux 
$

i.e. Bus 2 is missing.
Thanks
Glenn

**Comment by arfoll** [comment]
Merged. Thanks!

**Pull request closed without merging**
