### PR TITLE
Adding additional static library target that shows up as libmraa.a

### PR DESCRIPTION
**Pull request by anonymouse64**
Adding additional static library target for linking statically against libmraa.

### CODE REVIEW

**Comment by arfoll** [comment]
So this forces cmake to build both rather than what the system vars/cmake toolchain file decides, so I'm not sure I like it. At the same time, it's handy. Would you object to having this under a cmake var like -DBUILDBOTH=ON (or if you have a better name) ? And having the default stay the same?

**Comment by anonymouse64** [comment]
Yes, that would be sensible as most cases you probably just want the dynamic library, not the static one

**Comment by arfoll** [comment]
So if all you want is to have just a static library you can just use ` -DBUILD_SHARED_LIBS=OFF`. That's why we moved from specifying DYNAMIC to not specifying anything and letting users choose. I've added a note in the docs with fc03ea4816264ca9f900b42dda2b369209cb8543.

In any case if you think having both is useful and guard it with an option flag I'm happy to merge that.

**Comment by anonymouse64** [comment]
Ah I wasn't aware of this CMake option, this accomplishes the same task, I don't think that building both is necessary. Thanks

**Pull request closed without merging**
