### PR TITLE
mraa: SoFIA 3GR platform

### PR DESCRIPTION
**Pull request by laykuanloon**
Add SoFIA 3GR platform file and define 4 i2c controller.

Signed-off-by: Lay, Kuan Loon <kuan.loon.lay@intel.com>

### CODE REVIEW

**Comment by alext-mkrs** [comment]
And this one is proposed for `iio-api`, but it fits `master` much more (the opposite of PR #372). Looks like a small mixup?

**Comment by laykuanloon** [comment]
SoFIA using iio-api to access the sensor. So I just add this into iio-api branch and wait for everything in iio-api branch merge into master branch.

**Comment by arfoll** [comment]
@alext-mkrs @laykuanloon yes, let's keep all of this in iio-api branch for now, sofia platform is best left there until we have everything in master.

**Comment by alext-mkrs** [comment]
Ok, makes sense.

**Comment by arfoll** [comment]
Merged, thanks

**Pull request closed without merging**
