### PR TITLE
Update platform_checks.py

### PR DESCRIPTION
**Pull request by nicolalunghiemutex**
Resolve the error on platform different than edison

### CODE REVIEW

**Comment by nicolalunghiemutex** [comment]
Sorry I forgot
now should be ok

**Comment by alext-mkrs** [comment]
Why do we need the PlatformChecks class, if it'sjust "pass"?

**Comment by nicolalunghiemutex** [comment]
To remember to put something in it :-)
The problem is that the current platform check code fails on my board -> they are only for edison I think?
and we have a test bench for it and every time complains about the failed test

**Comment by arfoll** [comment]
Merged

**Pull request closed without merging**
