### PR TITLE
JavaScript: fixes and remove useless code

### PR DESCRIPTION
**Pull request by xbolshe**
Signed-off-by: Eugene Bolshakov <pub@relvarsoft.com>

Using ::Copy instead ::New is more correct.

### CODE REVIEW

**Comment by xbolshe** [comment]
Any code after SWIG_exception_fail will never be executed, because it will be "goto fail".

**Comment by arfoll** [comment]
Very good point on the exception_fail code :) Do you have any materials I could quickly read about using ::Copy instead of ::New? What versions of node did you test with?

Thanks!

**Comment by xbolshe** [comment]
Node 5.3.0. After switching to git version I have found again that SPI function response returns incorrect values while using ::New.

About materials: I used only source code of Node 5.3.0. 

Please pay your attention that ::Copy creates internal buffer with malloc,
when ::New does not. It creates a problem when a source buffer is freed.


MaybeLocal<Object> Copy(Isolate* isolate, const char* data, size_t length) {
  Environment* env = Environment::GetCurrent(isolate);
  EscapableHandleScope handle_scope(env->isolate());
  Local<Object> obj;
  if (Buffer::Copy(env, data, length).ToLocal(&obj))
    return handle_scope.Escape(obj);
  return Local<Object>();
}

MaybeLocal<Object> Copy(Environment* env, const char* data, size_t length) {
  EscapableHandleScope scope(env->isolate());

  // V8 currently only allows a maximum Typed Array index of max Smi.
  if (length > kMaxLength) {
    return Local<Object>();
  }

  void* new_data;
  if (length > 0) {
    CHECK_NE(data, nullptr);
    new_data = malloc(length);
    if (new_data == nullptr)
      return Local<Object>();
    memcpy(new_data, data, length);
  } else {
    new_data = nullptr;
  }

  Local<ArrayBuffer> ab =
    ArrayBuffer::New(env->isolate(),
        new_data,
        length,
        ArrayBufferCreationMode::kInternalized);
  Local<Uint8Array> ui = Uint8Array::New(ab, 0, length);
  Maybe<bool> mb =
      ui->SetPrototype(env->context(), env->buffer_prototype_object());
  if (mb.FromMaybe(false))
    return scope.Escape(ui);

  // Object failed to be created. Clean up resources.
  free(new_data);
  return Local<Object>();
}





MaybeLocal<Object> New(Isolate* isolate, char* data, size_t length) {
  Environment* env = Environment::GetCurrent(isolate);
  EscapableHandleScope handle_scope(env->isolate());
  Local<Object> obj;
  if (Buffer::New(env, data, length).ToLocal(&obj))
    return handle_scope.Escape(obj);
  return Local<Object>();
} 

MaybeLocal<Object> New(Environment* env, char* data, size_t length) {
  EscapableHandleScope scope(env->isolate());

  if (length > 0) {
    CHECK_NE(data, nullptr);
    CHECK(length <= kMaxLength);
  }

  Local<ArrayBuffer> ab =
      ArrayBuffer::New(env->isolate(),
                       data,
                       length,
                       ArrayBufferCreationMode::kInternalized);
  Local<Uint8Array> ui = Uint8Array::New(ab, 0, length);
  Maybe<bool> mb =
      ui->SetPrototype(env->context(), env->buffer_prototype_object());
  if (mb.FromMaybe(false))
    return scope.Escape(ui);
  return Local<Object>();
}

**Comment by arfoll** [comment]
Thanks alot for taking the time to explain this to me :) Merged with ff6b304fd2225ed7147ae3e7d964fd37aa934e8f

**Pull request closed without merging**
