### PR TITLE
Change the install path of the Java bindings libraries

### PR DESCRIPTION
**Pull request by andreivasiliu2211**
Signed-off-by: Andrei Vasiliu <andrei.vasiliu@intel.com>

### CODE REVIEW

**Comment by alext-mkrs** [comment]
Looks like you have a second, unrelated, commit for Galileo in this pull request.

**Comment by arfoll** [comment]
Yeah the first one is too iotdk so I'm keeping it in the yocto metadata, the second one I'll give a quick spin and likely merge. For small patches I don't mind like this :)

**Comment by arfoll** [comment]
Thanks, closing PR.

**Comment by alext-mkrs** [comment]
Got it, no worries

**Pull request closed without merging**
