### PR TITLE
Support for Terasic De10-Nano Kit

### PR DESCRIPTION
**Pull request by Propanu**
For a full list of currently supported board variants, protocols and their status check the new altera-socfpga.md page.

### CODE REVIEW

**Comment by arfoll** [comment]
Merged as one commit, thanks!

**Comment by nicolalunghiemutex** [comment]
missed to add the id for it also in types.hpp?

**Comment by nicolalunghiemutex** [comment]
sorry the full path is  api/mraa/types.h

**Comment by Propanu** [comment]
It's there: `MRAA_ALTERA_SOCFPGA = 15,       /** < Terasic DE-Nano-SoC Board */`

**Pull request closed without merging**
