### PR TITLE
Add JavaScript mraaStub project

### PR DESCRIPTION
**Pull request by dantler**
Signed-off-by: David Antler <david.a.antler@intel.com>

### CODE REVIEW

**Comment by dantler** [comment]
First PR.  I'm looking for feedback.

Please note that this is very Windows-specific.  Also note that mraaStub has not been added to npm (yet), although `jsstub/README` implies that it has been!

**Comment by alext-mkrs** [comment]
FWIW, that's an interesting idea, though it mixes up low-level functions from mraa domain with actual "device" functionality, which is more of a UPM domain.

And to be honest  I'd rather approach this from a more generic prospective and implement this in mraa itself, so that it's available from all languages mraa supports and not only JS.

This could also solve a problem with someone developing on Windows and needing an IDE autocomplete.

Interesting coincidence with an update in issue #44, it would seem that mocking mraa functionality is suddenly a hot topic :smiley:

**Comment by dantler** [comment]
@alext-mkrs Thanks for taking a look!  The purpose of this library was to allow emulation of a device's specification.  Generally the use case is to write code to target a device that isn't available or may not yet exist.  This has been very useful for me!  

Agreed that mraa is the right place for this item.  It would be nice to support all languages and bindings that mraa supports!  However, I think that task would be complex (you might end up building a real emulator!), and the unit testing culture might be strongest among JavaScript developers anyway.  Has anyone outside of nodejs users requested something like this?

Which autocomplete do you support?  Is there something I could add to support autocomplete?

**Comment by arfoll** [comment]
I've merged this as is (with a slight change in Readme to point to npm as 'future'). We'll try make this API complete and then use it as the basis for the JS docs instead of our current hack. Autocomplete on IDE basically just means that mraa is a loadable & valid node.js lib on windows I don't think anything else is needed.

Thanks!

**Comment by dantler** [comment]
I did put a [mraaStub project up on npm](https://www.npmjs.com/package/mraaStub) and added @arfoll as a collaborator.  Please let me know if you want me to change anything.

**Pull request closed without merging**
