### PR TITLE
gpio.h: remove extraneous extern C declaration

### PR DESCRIPTION
**Pull request by jontrulson**
Signed-off-by: Jon Trulson <jtrulson@ics.com>

### CODE REVIEW

**Comment by jontrulson** [comment]
Is there anything else that needs to be done to get this fix committed?  It causes build problems with C based drivers.

**Comment by arfoll** [comment]
Not really, I'll take a good look at a bunch of PRS and merge tmrw. Sorry and thx for the poke

**Comment by jontrulson** [comment]
Thanks!

**Comment by arfoll** [comment]
Merged - would be interested in seeing what the issues with this are - can you link me to what failures have been happening?

**Comment by jontrulson** [comment]
Since the clause was not protected by an "#ifdef __cplusplus", any C code compiled with JAVACALLBACK or SWIGJAVA defined would fail, as 'extern "C" ...' isn't valid C.

Since the file is already properly protected via this guard at the top and bottom, this clause was not necessary anyway.

**Pull request closed without merging**
