### PR TITLE
joule: enable ISH_GPIOs and GPIO_22 exposed on J12 header

### PR DESCRIPTION
**Pull request by Propanu**
Signed-off-by: Mihai Tudor Panu <mihai.tudor.panu@intel.com>

### CODE REVIEW

**Comment by arfoll** [comment]
This is good but your strncpy limit character write to 8-1 yet you give strings that are 8+1. You need to change your naming to match the string length, I recommend just making them ISHIOn rather than ISHGPIOn?

**Comment by Propanu** [comment]
Forgot about the terminator. I'm ok with ISHIOn. In fact I think ISH_IOn will be a bit more readable and still fit. Alternatively we can also bump the limit up to MRAA_PIN_NAME_SIZE. Let me know which option you prefer.

**Comment by arfoll** [comment]
Let's just use ISH_IOn, increasing MRAA_PIN_NAME_SIZE will eat up more mem, if we can fit it in let's just do that :)

**Comment by Propanu** [comment]
Should be all good now!

**Comment by arfoll** [comment]
rebased as one and merged. Thanks!

**Pull request closed without merging**
