### PR TITLE
Align SPI bus numbering with reality on 5xx

### PR DESCRIPTION
**Pull request by alext-mkrs**
Follow-up on our discussion in #758

### CODE REVIEW

**Comment by arfoll** [comment]
@arunlee77 can you review this?

**Comment by alext-mkrs** [comment]
Thanks @Propanu. @arfoll, looks like @arunlee77 is OOO for a while, so I don't think he'll be able to review this any time soon. I've tested this on current BIOS (1H3) and ref-os-iot build (1705), using MMA7455 sensor (just reading "Who Am I" register). This change is also in a full agreement with the current [pin mapping document](https://www.intel.com/content/www/us/en/support/boards-and-kits/intel-joule-kits/000022494.html).

If you want me to test something else, I'd be glad to, otherwise I'd propose to merge not waiting for @arunlee77's review, given the relative simplicity of the change, @propanu's review and tests I've run.

**Comment by arfoll** [comment]
Agreed. I'll merge it on Monday unless you just do it ;-) I'm away from
computer this weekend.

**Comment by alext-mkrs** [comment]
Thanks! I'll do it later today, no worries.

**Pull request merged**
