### PR TITLE
Fix compiler warnings for ARM compilation

### PR DESCRIPTION
**Pull request by alext-mkrs**
I don't have actual ARM-based board to do a full testing, but the changes are obvious enough I think. If anyone in possession of a BBB or Phyboard or something else ARM is willing to test these, that'd be nice.

### CODE REVIEW

**Comment by alext-mkrs** [comment]
BTW, we should probably add compilation for various pre-set architectures into CI, to make sure we build those regularly, otherwise we always go over a default one and others may bitrot or at least get "dirty" like in this example of various warnings being there for a while.

**Comment by dnoliver** [comment]
@alext-mkrs I can help with doing ARM builds in Travis CI. Do you have any guidance on how to do it?

**Comment by Propanu** [comment]
@dnoliver, you'll have to setup a docker image with a cross-compiler. Check with @pylbert, as he already has a working solution for this, at least for UPM, that was never merged upstream.

**Comment by Mani-Sadhasivam** [comment]
@alext-mkrs Tested the PR on 96Boards platform Dragonboard410c(ARM). A single warning gets generated for beaglebone.

`/home/linaro/mraa/src/arm/beaglebone.c:379:18: warning: variable ‘uart3_enabled’ set but not used [-Wunused-but-set-variable]
     unsigned int uart3_enabled = 0;`

You might want to clean that as well. Other than this the build looks clean :-)

**Comment by alext-mkrs** [comment]
@dnoliver, what @propanu says would be the best. A simple, less than ideal, but still viable solution would be to add a line to existing configs, similar to the MOCK one. That will get this code path compiling each time at least (so we can capture such warnings or plain broken stuff).

@mani-sadhasivam, thanks a lot, that's very nice of you! That single warning is something I purposedly left out, as while we don't use that uart3 in Beaglebone, we may in the future, so I left that init code intact, even though it results in an unused variable. I've commented on this in the commit message BTW.

**Comment by alext-mkrs** [comment]
@arfoll, @propanu, @whbruce, if there are no objections by Saturday, I'll merge this as I think we have enough confidence.

**Comment by Propanu** [comment]
These changes look OK to me!

**Comment by alext-mkrs** [comment]
Thanks @Propanu, merged.

**Pull request merged**
