### PR TITLE
phyboard.c: set each length of snprintf() to defined MAX_SIZE

### PR DESCRIPTION
**Pull request by svlstriker**
Signed-off-by: Norbert Wesp <nwesp@phytec.de>

### CODE REVIEW

**Comment by alext-mkrs** [comment]
Wrong account, sorry for that - that was me. :) I'm using two accounts to split project notifications and sometimes that plays jokes on me.

**Comment by alext-mkrs** [comment]
@arfoll, do you think we could merge this one in? Do you maybe want *me* to do that, given it's quite straightforward and all builds/tests passed? :)

**Comment by arfoll** [comment]
You're more than welcome to merge patches like these in the future. But merged, sorry for the delay and thx for the reminder!

**Comment by alext-mkrs** [comment]
Thanks!

**Pull request closed without merging**
