### PR TITLE
Static & manual code analysis fixes - the next part

### PR DESCRIPTION
**Pull request by alext-mkrs**
This one marks finish for fixes of things marked as "bugs" in non-example code (there are also "smells", but we'll get to that later).

### CODE REVIEW

**Comment by alext-mkrs** [comment]
@arfoll, ping? These are basically trivial and I'd let them in right away by myself, but I just believe that additional review never hurts even if that's just a glance. :)

**Comment by alext-mkrs** [comment]
That's because it's actually not used in that "if" branch or after it, so it was flagged as meaningless. I've left the syslog message as the code actually does set the bus 6 up (we are on an Arduino board in that clause).

**Comment by arfoll** [comment]
Makes sense to me, all merged! Thanks!

**Comment by alex-ter** [comment]
Thanks!

**Pull request closed without merging**
