### PR TITLE
raspberry_pi.c: gpio mmaping over /dev/gpiomem

### PR DESCRIPTION
**Pull request by 4refr0nt**
Signed-off-by: Victor Brutskiy <4refr0nt@gmail.com>

### CODE REVIEW

**Comment by arfoll** [comment]
I like it, but can we not be cleverer? On mraa_init() inside the rpi can we not just check if /dev/gpiomem exists and if it does use that?

**Comment by 4refr0nt** [comment]
Other people may want work with `/dev/mem` only

**Comment by arfoll** [comment]
is there a reason to use /dev/mem when /dev/gpiomem is accesible?

**Comment by 4refr0nt** [comment]
I do not know, but it does not mean that no reasons

**Pull request closed without merging**
