### PR TITLE
Resolved compilation error for nodejs = v4.2.6

### PR DESCRIPTION
**Pull request by prashantsathe**
Added header path for node and v8

Signed-off-by: Prashant Sathe <prshntsathe@gmail.com>

### CODE REVIEW

**Comment by arfoll** [comment]
what distro are you using and where do you get your node.js binaries from? This seems quite odd

**Comment by prashantsathe** [comment]
$ lsb_release -a

No LSB modules are available.

Distributor ID: Ubuntu

Description: *Ubuntu 16.04 LTS*

Release: 16.04

Codename: xenial

$ nodejs -v

*v4.2.6*

$ node -v

*v4.2.6*

**Comment by arfoll** [comment]
I'm really surprised you need this. Are these the default node binaries? Can you try wipe your build/ dir and re-run cmake this could just be a cache issue. Also post the output of `cmake -LA ..` to dpaste.com

**Comment by prashantsathe** [comment]
wiped all contain in build/ but still facing same issue..

-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.8")
> -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found
> suitable version "2.7.11+", minimum required is "2.7")
> *ERROR *- node.h not found
> *ERROR *- v8.h not found
> CMake Error at
> /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148
> (message):
>   Could NOT find Nodejs (missing: NODEJS_INCLUDE_DIRS)
> Call Stack (most recent call first):
>   /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388
> (_FPHSA_FAILURE_MESSAGE)
>   cmake/modules/FindNodejs.cmake:52 (find_package_handle_standard_args)
>   src/javascript/CMakeLists.txt:1 (find_package)


Outout of  cmake -LA ..
http://dpaste.com/1X1EF3R

-Prashant

**Comment by arfoll** [comment]
@tingleby does this fix compilation of node bindings on ubuntu in our PPA pkgs?

**Comment by alext-mkrs** [comment]
Looking at this once again it seems like it may have been fixed with my commit 139d42d0841c43f2237de8742857b3a2b2c5bdc6, probably the key here is not Node version, but Ubuntu's

**Comment by arfoll** [comment]
Indeed, I did wonder why this was still here, thanks!

**Pull request closed without merging**
