### PR TITLE
firmata: use correct i2c continuous read bits (0b00000010)

### PR DESCRIPTION
**Pull request by rwaldron**
Signed-off-by: Rick Waldron <waldron.rick@gmail.com>

### CODE REVIEW

**Comment by arfoll** [comment]
Thanks. Merged onto rebased firmata branch with qatest branch.

**Comment by rwaldron** [comment]
Should this be present in https://github.com/intel-iot-devkit/mraa/commits/qatest ? or https://github.com/intel-iot-devkit/mraa/commits/firmata ? It's in neither at the moment

**Comment by arfoll** [comment]
My bad it's in, I rebased the branch with some changes from the qatest branch.

**Comment by rwaldron** [comment]
Ah—thanks!

**Pull request closed without merging**
