### PR TITLE
Normalized function names in x86 platform

### PR DESCRIPTION
**Pull request by nicolalunghiemutex**
Normalized function names, set in the form mraa_[board name]_[function name]

### CODE REVIEW

**Comment by arfoll** [comment]
Thanks for the PRs. Note that they cannot be merged until you sign them off as explained in our CONTRIBUTING.md file.

**Comment by nicolalunghiemutex** [comment]
Signed-off-by: Nicola Lunghi <nicola.lunghi@emutex.com>

**Comment by arfoll** [comment]
It isn't enough to put the sign off here as a comment, it has to be embedded into your commits in the comment section, something like `git rebase -i HEAD~3` then select edit for each commit, then `git commit --amend -s` should create the sign off and then `git rebase --continue` to see the next one. Once all signed off `git push --force` to force the changes.

**Comment by nicolalunghiemutex** [comment]
Here you go thanks

**Comment by arfoll** [comment]
Rebased a little so 2&3 are together and fixup the names. Thanks alot for the fixes!

**Comment by nicolalunghiemutex** [comment]
Thank to you!
ps 
maybe the
set_pininfo function could be inserted in a top module and then all the x86 module could be refactored to use it??

```
mraa_set_pininfo(b, 0, "INVALID", (mraa_pincapabilities_t){ 0, 0, 0, 0, 0, 0, 0, 0 }, -1);

...

mraa_set_pininfo(mraa_board_t* board, int mraa_index, char* name, mraa_pincapabilities_t caps, int sysfs_pin)
{
    if (mraa_index < board->phy_pin_count) {
        mraa_pininfo_t* pin_info = &board->pins[mraa_index];
        strncpy(pin_info->name, name, MAX_LENGTH);
        pin_info->capabilities = caps;
        if (caps.gpio) {
            pin_info->gpio.pinmap = sysfs_pin;
            pin_info->gpio.mux_total = 0;
        }
        if (caps.i2c) {
            pin_info->i2c.pinmap = 1;
            pin_info->i2c.mux_total = 0;
        }
        if (caps.pwm) {
            int controller = 0;
            if (strncmp(name, "PWM", 3) == 0 && strlen(name) > 3 && isdigit(name[3]))
                controller = name[3] - '0';
            pin_info->pwm.parent_id = (unsigned int) controller;
            pin_info->pwm.pinmap = 0;
            pin_info->pwm.mux_total = 0;
        }
        if (caps.spi) {
            pin_info->spi.mux_total = 0;
        }
        if (caps.aio) {
            pin_info->aio.mux_total = 0;
            pin_info->aio.pinmap = 0;
        }
        if (caps.uart) {
            pin_info->uart.mux_total = 0;
        }
        return MRAA_SUCCESS;
    }
    return MRAA_ERROR_INVALID_RESOURCE;
}
```

**Pull request closed without merging**
