### PR TITLE
Fixing Beaglebone module to work with kernel 4.x.

### PR DESCRIPTION
**Pull request by nrcrast**
Made a few issues under my work account, @ncrastanaren.

* No more loading of individual peripheral capes. In 4.x, it's preferred to use a universal cape and configure the pins during initialization.
* PWM uses pwmchipX interface
* General cleanup of pin definitions. Created macro BUILD_PIN that's a little bit easier to look at, so you don't have to do the mental math of converting, for example, pin 76 -> P9_30

Signed-off-by: Nick Crast <nrcrast@gmail.com>

### CODE REVIEW

**Comment by nrcrast** [comment]
Tested: I2C, SPI, PWM

**Comment by arfoll** [comment]
@svlstriker can you take a look at this? I'd like to merge this but don't want to break the phyboard stuff either.

**Comment by nrcrast** [comment]
UART was also broken. At some point the higher level uart interface started using uart_dev->device_path, which isn't set in the beaglebone module. Fixed in latest pair of commits.

**Comment by nrcrast** [comment]
There also seems to be a problem with the ADC that I am chasing down. You have some math in aio.c:
`pin = aio + board->gpio_count;`

This doesn't really work with the BBB, the gpio_count is currently 45, but looking at the pinout the AIN pins start at 81. 

Why doesn't this function just accept the raw pin like others do?

**Comment by arfoll** [comment]
Closed as #750 contains this fix.

**Pull request closed without merging**
