### PR TITLE
raspberry_pi.c: gpio mmaping over /dev/gpiomem, Raspberry Pi 3 support

### PR DESCRIPTION
**Pull request by 4refr0nt**
Signed-off-by: Victor Brutskiy <4refr0nt@gmail.com>

### CODE REVIEW

**Comment by arfoll** [comment]
Hi victor, I'm seeing a lot of these opening and closing, I'd love to see rpi3 support is there anything I can do to help? Also in case you didn't know you can keep a PR open and keep pushing to the branch/rebase and I can mark it as WIP if you'd like

**Comment by 4refr0nt** [comment]
Hi!
I'm found some bugs in last commit, and will be fix. At now, RPI3 not detected correctly.
```
Apr 14 11:07:26 raspberrypi libmraa[6372]: libmraa version v0.10.1 initialised by user 'pi' with EUID 1000
Apr 14 11:07:26 raspberrypi libmraa[6372]: libmraa initialised for platform 'Raspberry Pi Model B Rev 1' of type 5
Apr 14 11:07:26 raspberrypi libmraa[6372]: libmraa version v0.10.1-4-g25611dd initialised by user 'pi' with EUID 1000
Apr 14 11:07:26 raspberrypi libmraa[6372]: libmraa initialised for platform 'Raspberry Pi 3 Model B Rev 1' of type 5
```

**Comment by alext-mkrs** [comment]
You are running it as unprivileged user - as of now mraa doesn't support this mode, give it a try as root.

Or you'll need to tweak sysfs permissions for gpio, there's a feature request open, where @tingleby has started some work.

**Comment by 4refr0nt** [comment]
I'm already test MRAA with /dev/gpiomem (and working good), but troubles with MRAA+UPM. When I'm use MRAA gpio - no problem, but when I'm use MRAA+UPM SX1276, then not good (/sys/class/gpio/xxx links not created). This troubles with JS only, in C++ examples all works good.

**Comment by arfoll** [comment]
That's very odd if C++ works and JS doesn't. Check that you are linking against the right libmraa.so to mraa.node, the way the linking/rpath is done now can get a little confusing.

**Comment by 4refr0nt** [comment]
I'm got error `new jsupm.SX1276 [Error: Illegal arguments for construction of _exports_SX1276]`
See strace fragment for details:
```
write(11, "try new modem\n", 14try new modem
)        = 14
cacheflush(0x5ce5b880, 0x5ce5b88c, 0, 0x1952b58, 0xc) = 0
cacheflush(0x5ce5b9a0, 0x5ce5b9ac, 0, 0x1952b58, 0xc) = 0
cacheflush(0x5ce5bde0, 0x5ce5bdec, 0, 0x1952b58, 0xc) = 0
cacheflush(0x5ce5bfa0, 0x5ce5bfac, 0, 0x1952b58, 0xc) = 0
cacheflush(0x5ce5c240, 0x5ce5c24c, 0, 0x1952b58, 0xc) = 0
cacheflush(0x5ce5c6c0, 0x5ce5c6cc, 0, 0x1952b58, 0xc) = 0
stat64("/dev/spidev0.0", {st_mode=S_IFCHR|0660, st_rdev=makedev(153, 0), ...}) = 0
open("/dev/spidev0.0", O_RDWR)          = 15
ioctl(15, 0x80046b04, 0x7eb9e568)       = 0
ioctl(15, 0x40016b01, 0x7eb9e557)       = 0
ioctl(15, 0x40016b02, 0x7eb9e557)       = 0
ioctl(15, 0x80016b02, 0x7eb9e557)       = 0
ioctl(15, 0x40016b03, 0x7eb9e550)       = 0
stat64("/sys/class/gpio/gpio8/", 0x7eb9e448) = -1 ENOENT (No such file or directory)
open("/sys/class/gpio/export", O_WRONLY) = 16
write(16, "8", 1)                       = 1
close(16)                               = 0
stat64("/sys/class/gpio/gpio17/", 0x7eb9e448) = -1 ENOENT (No such file or directory)
open("/sys/class/gpio/export", O_WRONLY) = 16
write(16, "17", 2)                      = 2
close(16)                               = 0
stat64("/sys/class/gpio/gpio23/", 0x7eb9e448) = -1 ENOENT (No such file or directory)
open("/sys/class/gpio/export", O_WRONLY) = 16
write(16, "23", 2)                      = 2
close(16)                               = 0
stat64("/sys/class/gpio/gpio27/", 0x7eb9e448) = -1 ENOENT (No such file or directory)
open("/sys/class/gpio/export", O_WRONLY) = 16
write(16, "27", 2)                      = 2
close(16)                               = 0
stat64("/sys/class/gpio/gpio22/", 0x7eb9e448) = -1 ENOENT (No such file or directory)
open("/sys/class/gpio/export", O_WRONLY) = 16
write(16, "22", 2)                      = 2
close(16)                               = 0
stat64("/sys/class/gpio/gpio5/", 0x7eb9e448) = -1 ENOENT (No such file or directory)
open("/sys/class/gpio/export", O_WRONLY) = 16
write(16, "5", 1)                       = 1
close(16)                               = 0
stat64("/sys/class/gpio/gpio6/", 0x7eb9e448) = -1 ENOENT (No such file or directory)
open("/sys/class/gpio/export", O_WRONLY) = 16
write(16, "6", 1)                       = 1
close(16)                               = 0
stat64("/sys/class/gpio/gpio13/", 0x7eb9e448) = -1 ENOENT (No such file or directory)
open("/sys/class/gpio/export", O_WRONLY) = 16
write(16, "13", 2)                      = 2
close(16)                               = 0
ioctl(15, 0x40016b01, 0x7eb9e637)       = 0
ioctl(15, 0x80046b04, 0x7eb9e634)       = 0
gettimeofday({1460976523, 941535}, NULL) = 0
send(10, "<140>Apr 18 15:48:43 libmraa[167"..., 85, MSG_NOSIGNAL) = 85
open("/sys/class/gpio/gpio8/direction", O_RDWR) = -1 EACCES (Permission denied)
open("/dev/gpiomem", O_RDWR)            = 16
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_SHARED, 16, 0x3f200000) = 0x76f11000
open("/sys/class/gpio/gpio17/direction", O_RDWR) = -1 EACCES (Permission denied)
nanosleep({0, 10000000}, NULL)          = 0
open("/sys/class/gpio/gpio23/direction", O_RDWR) = -1 EACCES (Permission denied)
open("/sys/class/gpio/gpio23/edge", O_RDWR) = -1 EACCES (Permission denied)
gettimeofday({1460976523, 962176}, NULL) = 0
send(10, "<139>Apr 18 15:48:43 libmraa[167"..., 74, MSG_NOSIGNAL) = 74
open("/sys/class/gpio/unexport", O_WRONLY) = 17
write(17, "13", 2)                      = 2
close(17)                               = 0
open("/sys/class/gpio/unexport", O_WRONLY) = 17
write(17, "6", 1)                       = 1
close(17)                               = 0
open("/sys/class/gpio/unexport", O_WRONLY) = 17
write(17, "5", 1)                       = 1
close(17)                               = 0
open("/sys/class/gpio/unexport", O_WRONLY) = 17
write(17, "22", 2)                      = 2
close(17)                               = 0
open("/sys/class/gpio/unexport", O_WRONLY) = 17
write(17, "27", 2)                      = 2
close(17)                               = 0
open("/sys/class/gpio/unexport", O_WRONLY) = 17
write(17, "23", 2)                      = 2
close(17)                               = 0
open("/sys/class/gpio/unexport", O_WRONLY) = 17
write(17, "17", 2)                      = 2
close(17)                               = 0
open("/sys/class/gpio/unexport", O_WRONLY) = 17
write(17, "8", 1)                       = 1
close(17)                               = 0
close(15)                               = 0
```
But when I'm use MRAA only (without UPM) - all ok
```
write(10, "Test pin 22\n", 12Test pin 22
)          = 12
stat64("/sys/class/gpio/gpio25/", {st_mode=S_IFDIR|0770, st_size=0, ...}) = 0
open("/dev/gpiomem", O_RDWR)            = 14
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_SHARED, 14, 0x3f200000) = 0x76fec000
write(10, "MMAP: OK\n", 9MMAP: OK
)              = 9
open("/sys/class/gpio/gpio25/direction", O_RDWR) = 15
write(15, "in", 2)                      = 2
close(15)                               = 0
open("/sys/class/gpio/gpio25/direction", O_RDWR) = 15
write(15, "out", 3)                     = 3
close(15)                               = 0
write(10, "Tests write 1 !\n", 16Tests write 1 !
)      = 16
```

**Comment by arfoll** [comment]
check the results of `ldd` on both mraa's mraa.node and upm's jsupm_sx1276.node

**Comment by 4refr0nt** [comment]
nothins important (also, I'm not use modules from local folder `node_modules` or from `/usr/lib/node_modules`, always using from global `/usr/local/lib/node_modules` only), and already try find library and module dublicates `find / | grep lib_name`, but found only one version.
```
pi@rpi:/usr/local/lib/node_modules/mraa/build/Release $ ldd ./mraa.node
        linux-vdso.so.1 (0x7ef56000)
        /usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76f04000)
        libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0x76e0d000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76d92000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x76d65000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76d3d000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76bfc000)
        /lib/ld-linux-armhf.so.3 (0x54b34000)
pi@rpi:/usr/local/lib/node_modules/jsupm_sx1276 $ ldd ./jsupm_sx1276.node
        linux-vdso.so.1 (0x7ed89000)
        /usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76f53000)
        libmraa.so.0 => /usr/local/lib/libmraa.so.0 (0x76f1f000)
        libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0x76e28000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76dad000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x76d80000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76c3f000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76c16000)
        /lib/ld-linux-armhf.so.3 (0x54ac3000)
```

**Comment by arfoll** [comment]
Something is wrong with your mraa.node, it's not build against libmraa.so. You've built it from npm rather than from sources so you're getting different stuff. Try building it again from cmake and make rather than the npm method.

**Comment by 4refr0nt** [comment]
`sudo npm remove -g mraa` then `make && make install`
pi@rpi:/usr/local/lib/node_modules/mraa $ ldd ./mraa.node
        linux-vdso.so.1 (0x7efba000)
        /usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76ebe000)
        libmraa.so.0 => /home/pi/!lora/mraa-new2/build/src/libmraa.so.0 (0x76e8a000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76e47000)
        libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0x76d6b000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76cf0000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x76cc3000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76b81000)
        /lib/ld-linux-armhf.so.3 (0x54ac2000)
```
but got error
```
stat64("/sys/class/gpio/gpio6/", 0x7e8bc570) = -1 ENOENT (No such file or directory)
open("/sys/class/gpio/export", O_WRONLY) = 15
write(15, "6", 1)                       = 1
close(15)                               = 0
stat64("/sys/class/gpio/gpio13/", 0x7e8bc570) = -1 ENOENT (No such file or directory)
open("/sys/class/gpio/export", O_WRONLY) = 15
write(15, "13", 2)                      = 2
close(15)                               = 0
ioctl(14, 0x40016b01, 0x7e8bc75f)       = 0
ioctl(14, 0x80046b04, 0x7e8bc75c)       = 0
gettimeofday({1461073682, 428782}, NULL) = 0
send(13, "<140>Apr 19 18:48:02 libmraa[314"..., 85, MSG_NOSIGNAL) = 85
open("/sys/class/gpio/gpio8/direction", O_RDWR) = 15
write(15, "out", 3)                     = 3
close(15)                               = 0
open("/dev/gpiomem", O_RDWR)            = 15
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_SHARED, 15, 0x3f200000) = 0x76f5d000
open("/sys/class/gpio/gpio17/direction", O_RDWR) = -1 EACCES (Permission denied)
nanosleep({0, 10000000}, NULL)          = 0
open("/sys/class/gpio/gpio23/direction", O_RDWR) = -1 EACCES (Permission denied)
open("/sys/class/gpio/gpio23/edge", O_RDWR) = -1 EACCES (Permission denied)
gettimeofday({1461073682, 444849}, NULL) = 0
send(13, "<139>Apr 19 18:48:02 libmraa[314"..., 74, MSG_NOSIGNAL) = 74
open("/sys/class/gpio/unexport", O_WRONLY) = 16
```
`No jsupm_sx1276 [Error: Illegal arguments for construction of _exports_SX1276]`

**Comment by arfoll** [comment]
To be honest those look like simple permission errors, what's the output of `journalctlf -f` as you run the code? Also what's the result when you run this as root?

**Comment by 4refr0nt** [comment]
after `sudo lfconfig` this problem solved (on my RaspberyPi 2), but I have some another problems on RaspberryPi 3. I'm wrote details later

**Pull request closed without merging**
