### PR TITLE
Error handling changes

### PR DESCRIPTION
**Pull request by wda2945**
Couldn’t resist the temptation!

Changed syslog messages and some error returns in i2c, pwm, uart, and gpio. Hopefully, fairly consistent.

Fixed lseek size problem in pwm.

Do as you will!

Signed-off-by: Martin G Lane-Smith <mlanesmith@gmail.com>

### CODE REVIEW

**Comment by arfoll** [comment]
I like alot of this, can you just add a sign off as explained in CONTRIBUTING.MD so I can merge the code (at least partly).

Thanks!

**Comment by wda2945** [comment]
I’ve added it to the pull request.

**Comment by arfoll** [comment]
Merged pretty much all of this, treated C++ issues/changes. Thanks alot for taking the time, the changes 100% make sense and hopefully make the API 'saner'. I'll release 1.0 due to this breaking/changing the public API.

**Comment by wda2945** [comment]
Thanks. BTW I only looked at the APIs I've used. I didn't look at adc, for example.

**Comment by arfoll** [comment]
I'm aware, i'll be changing those to match as well.

**Comment by arfoll** [comment]
on my radar is mraa_spi_write_word & mraa_aio_read, if you can see anything
else please shout.

**Comment by wda2945** [comment]
When I have time I'll take a look. There's nothing as relaxing as spending an evening reading code! 🤓

**Pull request closed without merging**
