### PR TITLE
docs: fix spelling errors

### PR DESCRIPTION
**Pull request by fboudra**
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>

### CODE REVIEW

**Comment by arfoll** [comment]
Thanks a lot for this, will merge when I get back on Friday.

Just for my info, do you have a tool that does this or did you find these
yourself? Might be something worth adding to the CI.

**Comment by fboudra** [comment]
Hi,

I'm in the process to package mraa for Debian (started a year ago by @tingleby on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780540). The package should be ready shortly and we run lintian (https://lintian.debian.org/) at the end of the build. Lintian is a QA tool that you can use as part of the CI.

**Comment by tingleby** [comment]
Yes I hadn't made much progress to be honest. I got hung up on how to split the language bindings. Would you like me to assign the ITP to you?

**Comment by arfoll** [comment]
Merged, thanks!

**Pull request closed without merging**
