### PR TITLE
JSON: Improve i2c and spi configuration.

### PR DESCRIPTION
**Pull request by whbruce**
Bus number no longer has to be the same as its id and all buses are disabled until a configuration entry is found. Also added Python sample for ADC on MinnowMax Calamari lure to validate JSON updates.

### CODE REVIEW

**Comment by arfoll** [comment]
This looks great @whbruce, will review on monday properly.

@Hbrinj want to take a look in the meantime?

**Comment by whbruce** [comment]
I forgot to mention that this PR also allows SPI slave select to be specified. This is critical for Intel Aero where it is non-zero.

**Comment by Hbrinj** [comment]
The latest I can check this out is next Friday if it is t merged then I'll go through it :)

**Comment by arfoll** [comment]
Merged. Thanks alot!

**Pull request closed without merging**
