### PR TITLE
Beaglebone: complete pwm output config & fix some warnings

### PR DESCRIPTION
**Pull request by SyrianSpock**
I only added the EHRPWM as outputs. Some EHRPWM outputs have to possible output pins, so maybe there should be a way for the user to chose but I don't know how to do that.
The ECAP should be treated as inputs for signal capture, so I didn't touch that.

### CODE REVIEW

**Comment by arfoll** [comment]
@SyrianSpock that looks great, thanks alot!

Can you just add your sign-off tp your commits (git commit --amend --signoff) to just show that you abide by the Developer's Certificate of Origin (same as the one used by the linux kernel). The exact rules are here: https://github.com/intel-iot-devkit/mraa/blob/master/docs/contributing.md.

**Comment by SyrianSpock** [comment]
Done

**Comment by SyrianSpock** [comment]
Just realised the pwm.pinmap parameter is not being set by beaglebone.c
I should probably add that.

**Comment by arfoll** [comment]
Thanks alot for working on this! All merged as of 2c4389c2a163831e3c8034b65c3f49061c892d1a

**Pull request closed without merging**
