### PR TITLE
JavaScript, Java and Python bindings now use libmraa.so instread of statically linking

### PR DESCRIPTION
**Pull request by whbruce**
This PR address #433 for JavaScript and Java, but no Python.  
0041801 is the Java update and is a significant change; look at commit message for details.
@petreeftime, please get Java team to review this update.

### CODE REVIEW

**Comment by arfoll** [comment]
Why is python not done? Any reason?

**Comment by whbruce** [comment]
I've never written any python code before so wouldn't feel comfortable making the update.  I guess I've got to get to grips with python sometime and it might as well be now. Just don't expect a quick fix....

**Comment by arfoll** [comment]
It should be really easy just requires the same thing as for nodejs. DW if
it doesn't work I'm happy to add it was just wondering if there was a
technical reason

**Comment by whbruce** [comment]
OK. Will give it a go.

**Comment by whbruce** [comment]
I got the Python binding working with dynamic linking but I realized a neater solution would be to use to adv_function table as an entry point for all binding specific code for the GPIO ISR. This would remove the binding language #ifdefs in gpio.c and make the code much neater. I'l work on this tomorrow for all bindings and hope to update PR by early next week.

**Comment by arfoll** [comment]
this likely won't work in node.js since that requires it to be done from C++ at least in the current methodology.

**Comment by whbruce** [comment]
I've left c++ code as is. It was the lack of Javascript native code in gpio.c that made the binding update so easy. No so luck with Java and Python. I'm testing with GPIO ISR samples for all languages to ensure my changes don't break anything.

**Comment by whbruce** [comment]
I have pushed updates for Java and added Python support. I enhanced gpio ISR samples so I could test with a specified pin and exercise shutdown.

**Comment by petreeftime** [comment]
The patch works for Java. I checked with the FTDITest example, but made use of UPM for the button and led.

**Comment by arfoll** [comment]
This is merged into the javacheck2 branch, please use that as the base for future commits. I still see some issues:

1. gpio raw mode is broken if we don't have a platform, setting lang_func needs to not depend on mraa_init() returning MRAA_SUCCESS or MRAA_ERROR_PLATFORM_ALREADY_INITIALISED for example MRAA_ERROR_PLATFORM_NOT_INITIALISED is perfectly valid. mraa_init() likely needs a small rework to return MRAA_SUCCESS to always create a MRAA_NULL_PLATFORM instead of just in USBPLAT usecase a little like done in the firmata branch.
2. This needs to be coverity clean, I added a check to the calloc on mraa_init for lang_func but I'm guessing it's not the only one... can someone run coverity or at least clang-analyzer and clean up the errors? Ping me if you need a hand there to run it in offline mode.

**Comment by arfoll** [comment]
This is basically all merged now. Thanks!

**Pull request closed without merging**
